version: "3.9"
services:
  mongodb:      
    build: ./mongodb
    image: mongodb
    container_name: mongodb  
    volumes:
      - ~/volumes/mongod/mongobingo/data:/data/db
      - ~/volumes/mongod/mongobingo/logs:/data/logs
    ports:
      - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=A2022
    command: mongod
    networks:
      mnet:
        aliases:
          - mongodb
          
  weather:
    image: weather     
    build: ./weather
    container_name: weather 
    links:
      - mongodb
    ports:
      - 2022:2022
    depends_on:     
      - mongodb  
    networks:
     - mnet
  
networks:
  mnet:
    driver: bridge
